name: Puzzles generation

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  gen-puzzle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate puzzles
        run: |
          ./scripts/setup.sh
          ./scripts/generate.sh 1
          ./scripts/generate.sh 2
          ./scripts/generate.sh 3
          ./scripts/generate.sh 4

      - name: Push generated puzzles
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          DATE=$(date "+%B %Y")
          git add .
          git commit -m "puzzles: $DATE"
          git push origin main
